export const RECEIVE_MESSAGES = "RECEIVE_MESSAGES";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const RECEIVE_THREAD = "RECEIVE_THREAD";
export const TOGGLE_MESSAGE_DETAIL = "TOGGLE_MESSAGE_DETAIL";
